package home.stanislavpoliakov.meet19_weather.domain.response_data;

public class WDailyData {
    public long time;
    public String summary;
    public String icon;
    public long sunriseTime;
    public long sunsetTime;
    public double moonPhase;
    public double precipIntensity;
    public double precipIntensityMax;
    public long precipIntensityMaxTime;
    public double precipProbability;
    public double precipAccumulation;
    public String precipType;
    public double temperatureHigh;
    public long temperatureHighTime;
    public double temperatureLow;
    public long temperatureLowTime;
    public double apparentTemperatureHigh;
    public long apparentTemperatureHighTime;
    public double apparentTemperatureLow;
    public long apparentTemperatureLowTime;
    public double dewPoint;
    public double humidity;
    public double pressure;
    public double windSpeed;
    public double windGust;
    public long windGustTime;
    public double windBearing;
    public double cloudCover;
    public double uvIndex;
    public long uvIndexTime;
    public double visibility;
    public double ozone;
    public double temperatureMin;
    public long temperatureMinTime;
    public double temperatureMax;
    public long temperatureMaxTime;
    public double apparentTemperatureMin;
    public long apparentTemperatureMinTime;
    public double apparentTemperatureMax;
    public long apparentTemperatureMaxTime;
}